import type { Address } from '@solana/kit';

import data from '../addresses.json' with { type: 'json' };
import type { PoolName, Stable, TokenSymbol, XStock } from './assets';

export type TokenInfo = {
    mint: Address;
    tokenProgram: Address;
    decimals: number;
    supportMint?: Address;
    pyth?: { feedId: string; proId: number };
};

export type PoolInfo = {
    address: Address;
    base: XStock;
    quote: Stable;
    token0Mint: Address;
    token1Mint: Address;
    token0Vault: Address;
    token1Vault: Address;
    lpMint: Address;
    observation: Address;
};

export type DevnetAddresses = {
    cpmm: { program: Address; ammConfig: Address };
    issuer: Address;
    treasury: Address;
    tokens: Record<TokenSymbol, TokenInfo>;
    pools: Record<PoolName, PoolInfo>;
};

/** Every public devnet address Laterite uses; generated by `just devnet-assets`. */
export const addresses = data as DevnetAddresses;

export type { PoolName, Stable, TokenSymbol, XStock } from './assets';
